FROM online-registry.cn-hongkong.cr.aliyuncs.com/okbase/golang:1.24-alpine3.21-okg1
RUN mkdir -p /workspace
COPY ./dist/xlayer-bridge /app/x1-bridge
COPY ./test/vectors /app/test/vectors
RUN apk update && apk add jq curl
EXPOSE 8080
EXPOSE 9090
CMD ["/bin/sh", "-c", "/app/x1-bridge run"]
