include version.mk

DOCKER_COMPOSE := docker compose -f docker-compose.yml

DOCKER_COMPOSE_REDIS := xlayer-bridge-redis
DOCKER_COMPOSE_BRIDGE_KAFKA := xlayer-bridge-coin-kafka
DOCKER_COMPOSE_BRIDGE_API := xlayer-bridge-service-api
DOCKER_COMPOSE_BRIDGE_PUSH := xlayer-bridge-service-push
DOCKER_COMPOSE_BRIDGE_TASK := xlayer-bridge-service-task

RUN_REDIS := $(DOCKER_COMPOSE) up -d $(DOCKER_COMPOSE_REDIS)
RUN_BRIDGE_KAFKA := $(DOCKER_COMPOSE) up -d $(DOCKER_COMPOSE_BRIDGE_KAFKA)
RUN_BRIDGE_API := $(DOCKER_COMPOSE) up -d $(DOCKER_COMPOSE_BRIDGE_API)
RUN_BRIDGE_PUSH := $(DOCKER_COMPOSE) up -d $(DOCKER_COMPOSE_BRIDGE_PUSH)
RUN_BRIDGE_TASK := $(DOCKER_COMPOSE) up -d $(DOCKER_COMPOSE_BRIDGE_TASK)

# This assumes you are running xlayer erigon locally.

run-kafka:
	$(RUN_BRIDGE_KAFKA)

run-api:
	$(RUN_DBS)
	$(RUN_REDIS)
	sleep 1
	$(RUN_BRIDGE_API)

run-push:
	$(RUN_DBS)
	$(RUN_REDIS)
	$(RUN_BRIDGE_KAFKA)
	sleep 2
	$(RUN_BRIDGE_PUSH)

run-task:
	$(RUN_DBS)
	$(RUN_REDIS)
	$(RUN_BRIDGE_KAFKA)
	sleep 2
	$(RUN_BRIDGE_TASK)

# NOTE: problem currently configured to cdk-erigon, not zkevm-node
run-all-xl:
	$(RUN_L1_NETWORK)
	sleep 5
	$(RUN_ZKPROVER)
	$(RUN_NODE)
	$(RUN_DBS)
	$(RUN_REDIS)
	$(RUN_BRIDGE_KAFKA)
	sleep 1
	$(RUN_BRIDGE_API)
	sleep 1
	$(RUN_BRIDGE_PUSH)
	$(RUN_BRIDGE_TASK)

test-full-xl: build-docker stop run-all-xl
	sleep 3
	trap '$(STOP)' EXIT; MallocNanoZone=0 go test -v -failfast -race -p 1 -timeout 2400s ./test/e2e/... -count 1 -tags='e2e'