// Code generated by mockery. DO NOT EDIT.

package mock_txcompressor

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	etherman "github.com/0xPolygonHermez/zkevm-bridge-service/etherman"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"

	types "github.com/0xPolygonHermez/zkevm-bridge-service/claimtxman/types"
)

// StorageInterface is an autogenerated mock type for the StorageInterface type
type StorageInterface struct {
	mock.Mock
}

type StorageInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageInterface) EXPECT() *StorageInterface_Expecter {
	return &StorageInterface_Expecter{mock: &_m.Mock}
}

// AddBlock provides a mock function with given fields: ctx, block, dbTx
func (_m *StorageInterface) AddBlock(ctx context.Context, block *etherman.Block, dbTx pgx.Tx) (uint64, error) {
	ret := _m.Called(ctx, block, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddBlock")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Block, pgx.Tx) (uint64, error)); ok {
		return rf(ctx, block, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Block, pgx.Tx) uint64); ok {
		r0 = rf(ctx, block, dbTx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *etherman.Block, pgx.Tx) error); ok {
		r1 = rf(ctx, block, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_AddBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlock'
type StorageInterface_AddBlock_Call struct {
	*mock.Call
}

// AddBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - block *etherman.Block
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) AddBlock(ctx interface{}, block interface{}, dbTx interface{}) *StorageInterface_AddBlock_Call {
	return &StorageInterface_AddBlock_Call{Call: _e.mock.On("AddBlock", ctx, block, dbTx)}
}

func (_c *StorageInterface_AddBlock_Call) Run(run func(ctx context.Context, block *etherman.Block, dbTx pgx.Tx)) *StorageInterface_AddBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.Block), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_AddBlock_Call) Return(_a0 uint64, _a1 error) *StorageInterface_AddBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_AddBlock_Call) RunAndReturn(run func(context.Context, *etherman.Block, pgx.Tx) (uint64, error)) *StorageInterface_AddBlock_Call {
	_c.Call.Return(run)
	return _c
}

// AddClaimTx provides a mock function with given fields: ctx, mTx, dbTx
func (_m *StorageInterface) AddClaimTx(ctx context.Context, mTx types.MonitoredTx, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, mTx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddClaimTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.MonitoredTx, pgx.Tx) error); ok {
		r0 = rf(ctx, mTx, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_AddClaimTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClaimTx'
type StorageInterface_AddClaimTx_Call struct {
	*mock.Call
}

// AddClaimTx is a helper method to define mock.On call
//   - ctx context.Context
//   - mTx types.MonitoredTx
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) AddClaimTx(ctx interface{}, mTx interface{}, dbTx interface{}) *StorageInterface_AddClaimTx_Call {
	return &StorageInterface_AddClaimTx_Call{Call: _e.mock.On("AddClaimTx", ctx, mTx, dbTx)}
}

func (_c *StorageInterface_AddClaimTx_Call) Run(run func(ctx context.Context, mTx types.MonitoredTx, dbTx pgx.Tx)) *StorageInterface_AddClaimTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.MonitoredTx), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_AddClaimTx_Call) Return(_a0 error) *StorageInterface_AddClaimTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_AddClaimTx_Call) RunAndReturn(run func(context.Context, types.MonitoredTx, pgx.Tx) error) *StorageInterface_AddClaimTx_Call {
	_c.Call.Return(run)
	return _c
}

// BeginDBTransaction provides a mock function with given fields: ctx
func (_m *StorageInterface) BeginDBTransaction(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginDBTransaction")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_BeginDBTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginDBTransaction'
type StorageInterface_BeginDBTransaction_Call struct {
	*mock.Call
}

// BeginDBTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StorageInterface_Expecter) BeginDBTransaction(ctx interface{}) *StorageInterface_BeginDBTransaction_Call {
	return &StorageInterface_BeginDBTransaction_Call{Call: _e.mock.On("BeginDBTransaction", ctx)}
}

func (_c *StorageInterface_BeginDBTransaction_Call) Run(run func(ctx context.Context)) *StorageInterface_BeginDBTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StorageInterface_BeginDBTransaction_Call) Return(_a0 pgx.Tx, _a1 error) *StorageInterface_BeginDBTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_BeginDBTransaction_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *StorageInterface_BeginDBTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx, dbTx
func (_m *StorageInterface) Commit(ctx context.Context, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) error); ok {
		r0 = rf(ctx, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type StorageInterface_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) Commit(ctx interface{}, dbTx interface{}) *StorageInterface_Commit_Call {
	return &StorageInterface_Commit_Call{Call: _e.mock.On("Commit", ctx, dbTx)}
}

func (_c *StorageInterface_Commit_Call) Run(run func(ctx context.Context, dbTx pgx.Tx)) *StorageInterface_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_Commit_Call) Return(_a0 error) *StorageInterface_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_Commit_Call) RunAndReturn(run func(context.Context, pgx.Tx) error) *StorageInterface_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaim provides a mock function with given fields: ctx, index, depositCount, networkID, dbTx
func (_m *StorageInterface) GetClaim(ctx context.Context, index uint32, depositCount uint32, networkID uint32, dbTx pgx.Tx) (*etherman.Claim, error) {
	ret := _m.Called(ctx, index, depositCount, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaim")
	}

	var r0 *etherman.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, uint32, pgx.Tx) (*etherman.Claim, error)); ok {
		return rf(ctx, index, depositCount, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, uint32, pgx.Tx) *etherman.Claim); ok {
		r0 = rf(ctx, index, depositCount, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, index, depositCount, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaim'
type StorageInterface_GetClaim_Call struct {
	*mock.Call
}

// GetClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - index uint32
//   - depositCount uint32
//   - networkID uint32
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) GetClaim(ctx interface{}, index interface{}, depositCount interface{}, networkID interface{}, dbTx interface{}) *StorageInterface_GetClaim_Call {
	return &StorageInterface_GetClaim_Call{Call: _e.mock.On("GetClaim", ctx, index, depositCount, networkID, dbTx)}
}

func (_c *StorageInterface_GetClaim_Call) Run(run func(ctx context.Context, index uint32, depositCount uint32, networkID uint32, dbTx pgx.Tx)) *StorageInterface_GetClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(uint32), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_GetClaim_Call) Return(_a0 *etherman.Claim, _a1 error) *StorageInterface_GetClaim_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetClaim_Call) RunAndReturn(run func(context.Context, uint32, uint32, uint32, pgx.Tx) (*etherman.Claim, error)) *StorageInterface_GetClaim_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaimTxsByStatus provides a mock function with given fields: ctx, statuses, rollupID, dbTx
func (_m *StorageInterface) GetClaimTxsByStatus(ctx context.Context, statuses []types.MonitoredTxStatus, rollupID uint32, dbTx pgx.Tx) ([]types.MonitoredTx, error) {
	ret := _m.Called(ctx, statuses, rollupID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimTxsByStatus")
	}

	var r0 []types.MonitoredTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.MonitoredTxStatus, uint32, pgx.Tx) ([]types.MonitoredTx, error)); ok {
		return rf(ctx, statuses, rollupID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.MonitoredTxStatus, uint32, pgx.Tx) []types.MonitoredTx); ok {
		r0 = rf(ctx, statuses, rollupID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MonitoredTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.MonitoredTxStatus, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, statuses, rollupID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetClaimTxsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimTxsByStatus'
type StorageInterface_GetClaimTxsByStatus_Call struct {
	*mock.Call
}

// GetClaimTxsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []types.MonitoredTxStatus
//   - rollupID uint32
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) GetClaimTxsByStatus(ctx interface{}, statuses interface{}, rollupID interface{}, dbTx interface{}) *StorageInterface_GetClaimTxsByStatus_Call {
	return &StorageInterface_GetClaimTxsByStatus_Call{Call: _e.mock.On("GetClaimTxsByStatus", ctx, statuses, rollupID, dbTx)}
}

func (_c *StorageInterface_GetClaimTxsByStatus_Call) Run(run func(ctx context.Context, statuses []types.MonitoredTxStatus, rollupID uint32, dbTx pgx.Tx)) *StorageInterface_GetClaimTxsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.MonitoredTxStatus), args[2].(uint32), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_GetClaimTxsByStatus_Call) Return(_a0 []types.MonitoredTx, _a1 error) *StorageInterface_GetClaimTxsByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetClaimTxsByStatus_Call) RunAndReturn(run func(context.Context, []types.MonitoredTxStatus, uint32, pgx.Tx) ([]types.MonitoredTx, error)) *StorageInterface_GetClaimTxsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaimTxsByStatusWithLimit provides a mock function with given fields: ctx, statuses, limit, offset, dbTx
func (_m *StorageInterface) GetClaimTxsByStatusWithLimit(ctx context.Context, statuses []types.MonitoredTxStatus, limit uint, offset uint, dbTx pgx.Tx) ([]types.MonitoredTx, error) {
	ret := _m.Called(ctx, statuses, limit, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimTxsByStatusWithLimit")
	}

	var r0 []types.MonitoredTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) ([]types.MonitoredTx, error)); ok {
		return rf(ctx, statuses, limit, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) []types.MonitoredTx); ok {
		r0 = rf(ctx, statuses, limit, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MonitoredTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) error); ok {
		r1 = rf(ctx, statuses, limit, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetClaimTxsByStatusWithLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimTxsByStatusWithLimit'
type StorageInterface_GetClaimTxsByStatusWithLimit_Call struct {
	*mock.Call
}

// GetClaimTxsByStatusWithLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []types.MonitoredTxStatus
//   - limit uint
//   - offset uint
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) GetClaimTxsByStatusWithLimit(ctx interface{}, statuses interface{}, limit interface{}, offset interface{}, dbTx interface{}) *StorageInterface_GetClaimTxsByStatusWithLimit_Call {
	return &StorageInterface_GetClaimTxsByStatusWithLimit_Call{Call: _e.mock.On("GetClaimTxsByStatusWithLimit", ctx, statuses, limit, offset, dbTx)}
}

func (_c *StorageInterface_GetClaimTxsByStatusWithLimit_Call) Run(run func(ctx context.Context, statuses []types.MonitoredTxStatus, limit uint, offset uint, dbTx pgx.Tx)) *StorageInterface_GetClaimTxsByStatusWithLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.MonitoredTxStatus), args[2].(uint), args[3].(uint), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_GetClaimTxsByStatusWithLimit_Call) Return(_a0 []types.MonitoredTx, _a1 error) *StorageInterface_GetClaimTxsByStatusWithLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetClaimTxsByStatusWithLimit_Call) RunAndReturn(run func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) ([]types.MonitoredTx, error)) *StorageInterface_GetClaimTxsByStatusWithLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeposit provides a mock function with given fields: ctx, depositCnt, networkID, dbTx
func (_m *StorageInterface) GetDeposit(ctx context.Context, depositCnt uint32, networkID uint32, dbTx pgx.Tx) (*etherman.Deposit, error) {
	ret := _m.Called(ctx, depositCnt, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeposit")
	}

	var r0 *etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) (*etherman.Deposit, error)); ok {
		return rf(ctx, depositCnt, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) *etherman.Deposit); ok {
		r0 = rf(ctx, depositCnt, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, depositCnt, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeposit'
type StorageInterface_GetDeposit_Call struct {
	*mock.Call
}

// GetDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCnt uint32
//   - networkID uint32
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) GetDeposit(ctx interface{}, depositCnt interface{}, networkID interface{}, dbTx interface{}) *StorageInterface_GetDeposit_Call {
	return &StorageInterface_GetDeposit_Call{Call: _e.mock.On("GetDeposit", ctx, depositCnt, networkID, dbTx)}
}

func (_c *StorageInterface_GetDeposit_Call) Run(run func(ctx context.Context, depositCnt uint32, networkID uint32, dbTx pgx.Tx)) *StorageInterface_GetDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_GetDeposit_Call) Return(_a0 *etherman.Deposit, _a1 error) *StorageInterface_GetDeposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetDeposit_Call) RunAndReturn(run func(context.Context, uint32, uint32, pgx.Tx) (*etherman.Deposit, error)) *StorageInterface_GetDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepositsFromOtherL2ToClaim provides a mock function with given fields: ctx, destinationNetwork, dbTx
func (_m *StorageInterface) GetDepositsFromOtherL2ToClaim(ctx context.Context, destinationNetwork uint32, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, destinationNetwork, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDepositsFromOtherL2ToClaim")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, destinationNetwork, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, destinationNetwork, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, destinationNetwork, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetDepositsFromOtherL2ToClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepositsFromOtherL2ToClaim'
type StorageInterface_GetDepositsFromOtherL2ToClaim_Call struct {
	*mock.Call
}

// GetDepositsFromOtherL2ToClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - destinationNetwork uint32
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) GetDepositsFromOtherL2ToClaim(ctx interface{}, destinationNetwork interface{}, dbTx interface{}) *StorageInterface_GetDepositsFromOtherL2ToClaim_Call {
	return &StorageInterface_GetDepositsFromOtherL2ToClaim_Call{Call: _e.mock.On("GetDepositsFromOtherL2ToClaim", ctx, destinationNetwork, dbTx)}
}

func (_c *StorageInterface_GetDepositsFromOtherL2ToClaim_Call) Run(run func(ctx context.Context, destinationNetwork uint32, dbTx pgx.Tx)) *StorageInterface_GetDepositsFromOtherL2ToClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_GetDepositsFromOtherL2ToClaim_Call) Return(_a0 []*etherman.Deposit, _a1 error) *StorageInterface_GetDepositsFromOtherL2ToClaim_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetDepositsFromOtherL2ToClaim_Call) RunAndReturn(run func(context.Context, uint32, pgx.Tx) ([]*etherman.Deposit, error)) *StorageInterface_GetDepositsFromOtherL2ToClaim_Call {
	_c.Call.Return(run)
	return _c
}

// GetL1Deposits provides a mock function with given fields: ctx, exitRoot, dbTx
func (_m *StorageInterface) GetL1Deposits(ctx context.Context, exitRoot []byte, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, exitRoot, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetL1Deposits")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, exitRoot, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, exitRoot, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, pgx.Tx) error); ok {
		r1 = rf(ctx, exitRoot, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetL1Deposits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL1Deposits'
type StorageInterface_GetL1Deposits_Call struct {
	*mock.Call
}

// GetL1Deposits is a helper method to define mock.On call
//   - ctx context.Context
//   - exitRoot []byte
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) GetL1Deposits(ctx interface{}, exitRoot interface{}, dbTx interface{}) *StorageInterface_GetL1Deposits_Call {
	return &StorageInterface_GetL1Deposits_Call{Call: _e.mock.On("GetL1Deposits", ctx, exitRoot, dbTx)}
}

func (_c *StorageInterface_GetL1Deposits_Call) Run(run func(ctx context.Context, exitRoot []byte, dbTx pgx.Tx)) *StorageInterface_GetL1Deposits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_GetL1Deposits_Call) Return(_a0 []*etherman.Deposit, _a1 error) *StorageInterface_GetL1Deposits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetL1Deposits_Call) RunAndReturn(run func(context.Context, []byte, pgx.Tx) ([]*etherman.Deposit, error)) *StorageInterface_GetL1Deposits_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestTrustedGERByDeposit provides a mock function with given fields: ctx, depositCnt, networkID, destinationNetwork, dbTx
func (_m *StorageInterface) GetLatestTrustedGERByDeposit(ctx context.Context, depositCnt uint32, networkID uint32, destinationNetwork uint32, dbTx pgx.Tx) (common.Hash, error) {
	ret := _m.Called(ctx, depositCnt, networkID, destinationNetwork, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTrustedGERByDeposit")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, uint32, pgx.Tx) (common.Hash, error)); ok {
		return rf(ctx, depositCnt, networkID, destinationNetwork, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, uint32, pgx.Tx) common.Hash); ok {
		r0 = rf(ctx, depositCnt, networkID, destinationNetwork, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, depositCnt, networkID, destinationNetwork, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_GetLatestTrustedGERByDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTrustedGERByDeposit'
type StorageInterface_GetLatestTrustedGERByDeposit_Call struct {
	*mock.Call
}

// GetLatestTrustedGERByDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCnt uint32
//   - networkID uint32
//   - destinationNetwork uint32
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) GetLatestTrustedGERByDeposit(ctx interface{}, depositCnt interface{}, networkID interface{}, destinationNetwork interface{}, dbTx interface{}) *StorageInterface_GetLatestTrustedGERByDeposit_Call {
	return &StorageInterface_GetLatestTrustedGERByDeposit_Call{Call: _e.mock.On("GetLatestTrustedGERByDeposit", ctx, depositCnt, networkID, destinationNetwork, dbTx)}
}

func (_c *StorageInterface_GetLatestTrustedGERByDeposit_Call) Run(run func(ctx context.Context, depositCnt uint32, networkID uint32, destinationNetwork uint32, dbTx pgx.Tx)) *StorageInterface_GetLatestTrustedGERByDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(uint32), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_GetLatestTrustedGERByDeposit_Call) Return(_a0 common.Hash, _a1 error) *StorageInterface_GetLatestTrustedGERByDeposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_GetLatestTrustedGERByDeposit_Call) RunAndReturn(run func(context.Context, uint32, uint32, uint32, pgx.Tx) (common.Hash, error)) *StorageInterface_GetLatestTrustedGERByDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx, dbTx
func (_m *StorageInterface) Rollback(ctx context.Context, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx) error); ok {
		r0 = rf(ctx, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type StorageInterface_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) Rollback(ctx interface{}, dbTx interface{}) *StorageInterface_Rollback_Call {
	return &StorageInterface_Rollback_Call{Call: _e.mock.On("Rollback", ctx, dbTx)}
}

func (_c *StorageInterface_Rollback_Call) Run(run func(ctx context.Context, dbTx pgx.Tx)) *StorageInterface_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_Rollback_Call) Return(_a0 error) *StorageInterface_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_Rollback_Call) RunAndReturn(run func(context.Context, pgx.Tx) error) *StorageInterface_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClaimTx provides a mock function with given fields: ctx, mTx, dbTx
func (_m *StorageInterface) UpdateClaimTx(ctx context.Context, mTx types.MonitoredTx, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, mTx, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClaimTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.MonitoredTx, pgx.Tx) error); ok {
		r0 = rf(ctx, mTx, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_UpdateClaimTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClaimTx'
type StorageInterface_UpdateClaimTx_Call struct {
	*mock.Call
}

// UpdateClaimTx is a helper method to define mock.On call
//   - ctx context.Context
//   - mTx types.MonitoredTx
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) UpdateClaimTx(ctx interface{}, mTx interface{}, dbTx interface{}) *StorageInterface_UpdateClaimTx_Call {
	return &StorageInterface_UpdateClaimTx_Call{Call: _e.mock.On("UpdateClaimTx", ctx, mTx, dbTx)}
}

func (_c *StorageInterface_UpdateClaimTx_Call) Run(run func(ctx context.Context, mTx types.MonitoredTx, dbTx pgx.Tx)) *StorageInterface_UpdateClaimTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.MonitoredTx), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_UpdateClaimTx_Call) Return(_a0 error) *StorageInterface_UpdateClaimTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_UpdateClaimTx_Call) RunAndReturn(run func(context.Context, types.MonitoredTx, pgx.Tx) error) *StorageInterface_UpdateClaimTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateL1DepositStatus provides a mock function with given fields: ctx, depositCount, dbTx
func (_m *StorageInterface) UpdateL1DepositStatus(ctx context.Context, depositCount uint, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, depositCount, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateL1DepositStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, pgx.Tx) error); ok {
		r0 = rf(ctx, depositCount, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_UpdateL1DepositStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateL1DepositStatus'
type StorageInterface_UpdateL1DepositStatus_Call struct {
	*mock.Call
}

// UpdateL1DepositStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCount uint
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) UpdateL1DepositStatus(ctx interface{}, depositCount interface{}, dbTx interface{}) *StorageInterface_UpdateL1DepositStatus_Call {
	return &StorageInterface_UpdateL1DepositStatus_Call{Call: _e.mock.On("UpdateL1DepositStatus", ctx, depositCount, dbTx)}
}

func (_c *StorageInterface_UpdateL1DepositStatus_Call) Run(run func(ctx context.Context, depositCount uint, dbTx pgx.Tx)) *StorageInterface_UpdateL1DepositStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_UpdateL1DepositStatus_Call) Return(_a0 error) *StorageInterface_UpdateL1DepositStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_UpdateL1DepositStatus_Call) RunAndReturn(run func(context.Context, uint, pgx.Tx) error) *StorageInterface_UpdateL1DepositStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateL1DepositsStatus provides a mock function with given fields: ctx, exitRoot, destinationNetwork, dbTx
func (_m *StorageInterface) UpdateL1DepositsStatus(ctx context.Context, exitRoot []byte, destinationNetwork uint32, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, exitRoot, destinationNetwork, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateL1DepositsStatus")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint32, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, exitRoot, destinationNetwork, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint32, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, exitRoot, destinationNetwork, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, exitRoot, destinationNetwork, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_UpdateL1DepositsStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateL1DepositsStatus'
type StorageInterface_UpdateL1DepositsStatus_Call struct {
	*mock.Call
}

// UpdateL1DepositsStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - exitRoot []byte
//   - destinationNetwork uint32
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) UpdateL1DepositsStatus(ctx interface{}, exitRoot interface{}, destinationNetwork interface{}, dbTx interface{}) *StorageInterface_UpdateL1DepositsStatus_Call {
	return &StorageInterface_UpdateL1DepositsStatus_Call{Call: _e.mock.On("UpdateL1DepositsStatus", ctx, exitRoot, destinationNetwork, dbTx)}
}

func (_c *StorageInterface_UpdateL1DepositsStatus_Call) Run(run func(ctx context.Context, exitRoot []byte, destinationNetwork uint32, dbTx pgx.Tx)) *StorageInterface_UpdateL1DepositsStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(uint32), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_UpdateL1DepositsStatus_Call) Return(_a0 []*etherman.Deposit, _a1 error) *StorageInterface_UpdateL1DepositsStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_UpdateL1DepositsStatus_Call) RunAndReturn(run func(context.Context, []byte, uint32, pgx.Tx) ([]*etherman.Deposit, error)) *StorageInterface_UpdateL1DepositsStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateL1DepositsStatusXLayer provides a mock function with given fields: ctx, exitRoot, dbTx
func (_m *StorageInterface) UpdateL1DepositsStatusXLayer(ctx context.Context, exitRoot []byte, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, exitRoot, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateL1DepositsStatusXLayer")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, exitRoot, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, exitRoot, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, pgx.Tx) error); ok {
		r1 = rf(ctx, exitRoot, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_UpdateL1DepositsStatusXLayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateL1DepositsStatusXLayer'
type StorageInterface_UpdateL1DepositsStatusXLayer_Call struct {
	*mock.Call
}

// UpdateL1DepositsStatusXLayer is a helper method to define mock.On call
//   - ctx context.Context
//   - exitRoot []byte
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) UpdateL1DepositsStatusXLayer(ctx interface{}, exitRoot interface{}, dbTx interface{}) *StorageInterface_UpdateL1DepositsStatusXLayer_Call {
	return &StorageInterface_UpdateL1DepositsStatusXLayer_Call{Call: _e.mock.On("UpdateL1DepositsStatusXLayer", ctx, exitRoot, dbTx)}
}

func (_c *StorageInterface_UpdateL1DepositsStatusXLayer_Call) Run(run func(ctx context.Context, exitRoot []byte, dbTx pgx.Tx)) *StorageInterface_UpdateL1DepositsStatusXLayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_UpdateL1DepositsStatusXLayer_Call) Return(_a0 []*etherman.Deposit, _a1 error) *StorageInterface_UpdateL1DepositsStatusXLayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_UpdateL1DepositsStatusXLayer_Call) RunAndReturn(run func(context.Context, []byte, pgx.Tx) ([]*etherman.Deposit, error)) *StorageInterface_UpdateL1DepositsStatusXLayer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateL2DepositsStatus provides a mock function with given fields: ctx, exitRoot, rollupID, networkID, dbTx
func (_m *StorageInterface) UpdateL2DepositsStatus(ctx context.Context, exitRoot []byte, rollupID uint32, networkID uint32, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, exitRoot, rollupID, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateL2DepositsStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint32, uint32, pgx.Tx) error); ok {
		r0 = rf(ctx, exitRoot, rollupID, networkID, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageInterface_UpdateL2DepositsStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateL2DepositsStatus'
type StorageInterface_UpdateL2DepositsStatus_Call struct {
	*mock.Call
}

// UpdateL2DepositsStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - exitRoot []byte
//   - rollupID uint32
//   - networkID uint32
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) UpdateL2DepositsStatus(ctx interface{}, exitRoot interface{}, rollupID interface{}, networkID interface{}, dbTx interface{}) *StorageInterface_UpdateL2DepositsStatus_Call {
	return &StorageInterface_UpdateL2DepositsStatus_Call{Call: _e.mock.On("UpdateL2DepositsStatus", ctx, exitRoot, rollupID, networkID, dbTx)}
}

func (_c *StorageInterface_UpdateL2DepositsStatus_Call) Run(run func(ctx context.Context, exitRoot []byte, rollupID uint32, networkID uint32, dbTx pgx.Tx)) *StorageInterface_UpdateL2DepositsStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(uint32), args[3].(uint32), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_UpdateL2DepositsStatus_Call) Return(_a0 error) *StorageInterface_UpdateL2DepositsStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageInterface_UpdateL2DepositsStatus_Call) RunAndReturn(run func(context.Context, []byte, uint32, uint32, pgx.Tx) error) *StorageInterface_UpdateL2DepositsStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateL2DepositsStatusXLayer provides a mock function with given fields: ctx, exitRoot, rollupID, networkID, dbTx
func (_m *StorageInterface) UpdateL2DepositsStatusXLayer(ctx context.Context, exitRoot []byte, rollupID uint, networkID uint, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, exitRoot, rollupID, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateL2DepositsStatusXLayer")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint, uint, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, exitRoot, rollupID, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint, uint, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, exitRoot, rollupID, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, uint, uint, pgx.Tx) error); ok {
		r1 = rf(ctx, exitRoot, rollupID, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageInterface_UpdateL2DepositsStatusXLayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateL2DepositsStatusXLayer'
type StorageInterface_UpdateL2DepositsStatusXLayer_Call struct {
	*mock.Call
}

// UpdateL2DepositsStatusXLayer is a helper method to define mock.On call
//   - ctx context.Context
//   - exitRoot []byte
//   - rollupID uint
//   - networkID uint
//   - dbTx pgx.Tx
func (_e *StorageInterface_Expecter) UpdateL2DepositsStatusXLayer(ctx interface{}, exitRoot interface{}, rollupID interface{}, networkID interface{}, dbTx interface{}) *StorageInterface_UpdateL2DepositsStatusXLayer_Call {
	return &StorageInterface_UpdateL2DepositsStatusXLayer_Call{Call: _e.mock.On("UpdateL2DepositsStatusXLayer", ctx, exitRoot, rollupID, networkID, dbTx)}
}

func (_c *StorageInterface_UpdateL2DepositsStatusXLayer_Call) Run(run func(ctx context.Context, exitRoot []byte, rollupID uint, networkID uint, dbTx pgx.Tx)) *StorageInterface_UpdateL2DepositsStatusXLayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(uint), args[3].(uint), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *StorageInterface_UpdateL2DepositsStatusXLayer_Call) Return(_a0 []*etherman.Deposit, _a1 error) *StorageInterface_UpdateL2DepositsStatusXLayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageInterface_UpdateL2DepositsStatusXLayer_Call) RunAndReturn(run func(context.Context, []byte, uint, uint, pgx.Tx) ([]*etherman.Deposit, error)) *StorageInterface_UpdateL2DepositsStatusXLayer_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageInterface creates a new instance of StorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageInterface {
	mock := &StorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
