// Code generated by mockery. DO NOT EDIT.

package server

import (
	context "context"
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	etherman "github.com/0xPolygonHermez/zkevm-bridge-service/etherman"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v4"

	time "time"

	types "github.com/0xPolygonHermez/zkevm-bridge-service/claimtxman/types"
)

// bridgeServiceStorageMock is an autogenerated mock type for the bridgeServiceStorage type
type bridgeServiceStorageMock struct {
	mock.Mock
}

type bridgeServiceStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *bridgeServiceStorageMock) EXPECT() *bridgeServiceStorageMock_Expecter {
	return &bridgeServiceStorageMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key, dbTx
func (_m *bridgeServiceStorageMock) Get(ctx context.Context, key []byte, dbTx pgx.Tx) ([][]byte, error) {
	ret := _m.Called(ctx, key, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 [][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, pgx.Tx) ([][]byte, error)); ok {
		return rf(ctx, key, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, pgx.Tx) [][]byte); ok {
		r0 = rf(ctx, key, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, pgx.Tx) error); ok {
		r1 = rf(ctx, key, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type bridgeServiceStorageMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key []byte
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) Get(ctx interface{}, key interface{}, dbTx interface{}) *bridgeServiceStorageMock_Get_Call {
	return &bridgeServiceStorageMock_Get_Call{Call: _e.mock.On("Get", ctx, key, dbTx)}
}

func (_c *bridgeServiceStorageMock_Get_Call) Run(run func(ctx context.Context, key []byte, dbTx pgx.Tx)) *bridgeServiceStorageMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_Get_Call) Return(_a0 [][]byte, _a1 error) *bridgeServiceStorageMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_Get_Call) RunAndReturn(run func(context.Context, []byte, pgx.Tx) ([][]byte, error)) *bridgeServiceStorageMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBridgeBalance provides a mock function with given fields: ctx, originalTokenAddr, networkID, forUpdate, dbTx
func (_m *bridgeServiceStorageMock) GetBridgeBalance(ctx context.Context, originalTokenAddr common.Address, networkID uint, forUpdate bool, dbTx pgx.Tx) (*big.Int, error) {
	ret := _m.Called(ctx, originalTokenAddr, networkID, forUpdate, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetBridgeBalance")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint, bool, pgx.Tx) (*big.Int, error)); ok {
		return rf(ctx, originalTokenAddr, networkID, forUpdate, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint, bool, pgx.Tx) *big.Int); ok {
		r0 = rf(ctx, originalTokenAddr, networkID, forUpdate, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, uint, bool, pgx.Tx) error); ok {
		r1 = rf(ctx, originalTokenAddr, networkID, forUpdate, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetBridgeBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgeBalance'
type bridgeServiceStorageMock_GetBridgeBalance_Call struct {
	*mock.Call
}

// GetBridgeBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - originalTokenAddr common.Address
//   - networkID uint
//   - forUpdate bool
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetBridgeBalance(ctx interface{}, originalTokenAddr interface{}, networkID interface{}, forUpdate interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetBridgeBalance_Call {
	return &bridgeServiceStorageMock_GetBridgeBalance_Call{Call: _e.mock.On("GetBridgeBalance", ctx, originalTokenAddr, networkID, forUpdate, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetBridgeBalance_Call) Run(run func(ctx context.Context, originalTokenAddr common.Address, networkID uint, forUpdate bool, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetBridgeBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(uint), args[3].(bool), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetBridgeBalance_Call) Return(_a0 *big.Int, _a1 error) *bridgeServiceStorageMock_GetBridgeBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetBridgeBalance_Call) RunAndReturn(run func(context.Context, common.Address, uint, bool, pgx.Tx) (*big.Int, error)) *bridgeServiceStorageMock_GetBridgeBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaim provides a mock function with given fields: ctx, index, originNetworkID, networkID, dbTx
func (_m *bridgeServiceStorageMock) GetClaim(ctx context.Context, index uint32, originNetworkID uint32, networkID uint32, dbTx pgx.Tx) (*etherman.Claim, error) {
	ret := _m.Called(ctx, index, originNetworkID, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaim")
	}

	var r0 *etherman.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, uint32, pgx.Tx) (*etherman.Claim, error)); ok {
		return rf(ctx, index, originNetworkID, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, uint32, pgx.Tx) *etherman.Claim); ok {
		r0 = rf(ctx, index, originNetworkID, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, index, originNetworkID, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaim'
type bridgeServiceStorageMock_GetClaim_Call struct {
	*mock.Call
}

// GetClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - index uint32
//   - originNetworkID uint32
//   - networkID uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetClaim(ctx interface{}, index interface{}, originNetworkID interface{}, networkID interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetClaim_Call {
	return &bridgeServiceStorageMock_GetClaim_Call{Call: _e.mock.On("GetClaim", ctx, index, originNetworkID, networkID, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetClaim_Call) Run(run func(ctx context.Context, index uint32, originNetworkID uint32, networkID uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(uint32), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaim_Call) Return(_a0 *etherman.Claim, _a1 error) *bridgeServiceStorageMock_GetClaim_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaim_Call) RunAndReturn(run func(context.Context, uint32, uint32, uint32, pgx.Tx) (*etherman.Claim, error)) *bridgeServiceStorageMock_GetClaim_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaimCount provides a mock function with given fields: ctx, destAddr, dbTx
func (_m *bridgeServiceStorageMock) GetClaimCount(ctx context.Context, destAddr string, dbTx pgx.Tx) (uint64, error) {
	ret := _m.Called(ctx, destAddr, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pgx.Tx) (uint64, error)); ok {
		return rf(ctx, destAddr, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pgx.Tx) uint64); ok {
		r0 = rf(ctx, destAddr, dbTx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetClaimCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimCount'
type bridgeServiceStorageMock_GetClaimCount_Call struct {
	*mock.Call
}

// GetClaimCount is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetClaimCount(ctx interface{}, destAddr interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetClaimCount_Call {
	return &bridgeServiceStorageMock_GetClaimCount_Call{Call: _e.mock.On("GetClaimCount", ctx, destAddr, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetClaimCount_Call) Run(run func(ctx context.Context, destAddr string, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetClaimCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaimCount_Call) Return(_a0 uint64, _a1 error) *bridgeServiceStorageMock_GetClaimCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaimCount_Call) RunAndReturn(run func(context.Context, string, pgx.Tx) (uint64, error)) *bridgeServiceStorageMock_GetClaimCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaimTxById provides a mock function with given fields: ctx, id, dbTx
func (_m *bridgeServiceStorageMock) GetClaimTxById(ctx context.Context, id uint, dbTx pgx.Tx) (*types.MonitoredTx, error) {
	ret := _m.Called(ctx, id, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimTxById")
	}

	var r0 *types.MonitoredTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, pgx.Tx) (*types.MonitoredTx, error)); ok {
		return rf(ctx, id, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, pgx.Tx) *types.MonitoredTx); ok {
		r0 = rf(ctx, id, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MonitoredTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, pgx.Tx) error); ok {
		r1 = rf(ctx, id, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetClaimTxById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimTxById'
type bridgeServiceStorageMock_GetClaimTxById_Call struct {
	*mock.Call
}

// GetClaimTxById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetClaimTxById(ctx interface{}, id interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetClaimTxById_Call {
	return &bridgeServiceStorageMock_GetClaimTxById_Call{Call: _e.mock.On("GetClaimTxById", ctx, id, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetClaimTxById_Call) Run(run func(ctx context.Context, id uint, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetClaimTxById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaimTxById_Call) Return(_a0 *types.MonitoredTx, _a1 error) *bridgeServiceStorageMock_GetClaimTxById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaimTxById_Call) RunAndReturn(run func(context.Context, uint, pgx.Tx) (*types.MonitoredTx, error)) *bridgeServiceStorageMock_GetClaimTxById_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaimTxsByStatusWithLimit provides a mock function with given fields: ctx, statuses, limit, offset, dbTx
func (_m *bridgeServiceStorageMock) GetClaimTxsByStatusWithLimit(ctx context.Context, statuses []types.MonitoredTxStatus, limit uint, offset uint, dbTx pgx.Tx) ([]types.MonitoredTx, error) {
	ret := _m.Called(ctx, statuses, limit, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimTxsByStatusWithLimit")
	}

	var r0 []types.MonitoredTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) ([]types.MonitoredTx, error)); ok {
		return rf(ctx, statuses, limit, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) []types.MonitoredTx); ok {
		r0 = rf(ctx, statuses, limit, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MonitoredTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) error); ok {
		r1 = rf(ctx, statuses, limit, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimTxsByStatusWithLimit'
type bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call struct {
	*mock.Call
}

// GetClaimTxsByStatusWithLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []types.MonitoredTxStatus
//   - limit uint
//   - offset uint
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetClaimTxsByStatusWithLimit(ctx interface{}, statuses interface{}, limit interface{}, offset interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call {
	return &bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call{Call: _e.mock.On("GetClaimTxsByStatusWithLimit", ctx, statuses, limit, offset, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call) Run(run func(ctx context.Context, statuses []types.MonitoredTxStatus, limit uint, offset uint, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.MonitoredTxStatus), args[2].(uint), args[3].(uint), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call) Return(_a0 []types.MonitoredTx, _a1 error) *bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call) RunAndReturn(run func(context.Context, []types.MonitoredTxStatus, uint, uint, pgx.Tx) ([]types.MonitoredTx, error)) *bridgeServiceStorageMock_GetClaimTxsByStatusWithLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaims provides a mock function with given fields: ctx, destAddr, limit, offset, dbTx
func (_m *bridgeServiceStorageMock) GetClaims(ctx context.Context, destAddr string, limit uint32, offset uint32, dbTx pgx.Tx) ([]*etherman.Claim, error) {
	ret := _m.Called(ctx, destAddr, limit, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetClaims")
	}

	var r0 []*etherman.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, uint32, pgx.Tx) ([]*etherman.Claim, error)); ok {
		return rf(ctx, destAddr, limit, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, uint32, pgx.Tx) []*etherman.Claim); ok {
		r0 = rf(ctx, destAddr, limit, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, limit, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaims'
type bridgeServiceStorageMock_GetClaims_Call struct {
	*mock.Call
}

// GetClaims is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - limit uint32
//   - offset uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetClaims(ctx interface{}, destAddr interface{}, limit interface{}, offset interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetClaims_Call {
	return &bridgeServiceStorageMock_GetClaims_Call{Call: _e.mock.On("GetClaims", ctx, destAddr, limit, offset, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetClaims_Call) Run(run func(ctx context.Context, destAddr string, limit uint32, offset uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint32), args[3].(uint32), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaims_Call) Return(_a0 []*etherman.Claim, _a1 error) *bridgeServiceStorageMock_GetClaims_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetClaims_Call) RunAndReturn(run func(context.Context, string, uint32, uint32, pgx.Tx) ([]*etherman.Claim, error)) *bridgeServiceStorageMock_GetClaims_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeposit provides a mock function with given fields: ctx, depositCnt, networkID, dbTx
func (_m *bridgeServiceStorageMock) GetDeposit(ctx context.Context, depositCnt uint32, networkID uint32, dbTx pgx.Tx) (*etherman.Deposit, error) {
	ret := _m.Called(ctx, depositCnt, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeposit")
	}

	var r0 *etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) (*etherman.Deposit, error)); ok {
		return rf(ctx, depositCnt, networkID, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) *etherman.Deposit); ok {
		r0 = rf(ctx, depositCnt, networkID, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, depositCnt, networkID, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeposit'
type bridgeServiceStorageMock_GetDeposit_Call struct {
	*mock.Call
}

// GetDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCnt uint32
//   - networkID uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetDeposit(ctx interface{}, depositCnt interface{}, networkID interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetDeposit_Call {
	return &bridgeServiceStorageMock_GetDeposit_Call{Call: _e.mock.On("GetDeposit", ctx, depositCnt, networkID, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetDeposit_Call) Run(run func(ctx context.Context, depositCnt uint32, networkID uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetDeposit_Call) Return(_a0 *etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetDeposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetDeposit_Call) RunAndReturn(run func(context.Context, uint32, uint32, pgx.Tx) (*etherman.Deposit, error)) *bridgeServiceStorageMock_GetDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepositByHash provides a mock function with given fields: ctx, destAddr, networkID, txHash, dbTx
func (_m *bridgeServiceStorageMock) GetDepositByHash(ctx context.Context, destAddr string, networkID uint, txHash string, dbTx pgx.Tx) (*etherman.Deposit, error) {
	ret := _m.Called(ctx, destAddr, networkID, txHash, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDepositByHash")
	}

	var r0 *etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, string, pgx.Tx) (*etherman.Deposit, error)); ok {
		return rf(ctx, destAddr, networkID, txHash, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, string, pgx.Tx) *etherman.Deposit); ok {
		r0 = rf(ctx, destAddr, networkID, txHash, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, string, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, networkID, txHash, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetDepositByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepositByHash'
type bridgeServiceStorageMock_GetDepositByHash_Call struct {
	*mock.Call
}

// GetDepositByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - networkID uint
//   - txHash string
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetDepositByHash(ctx interface{}, destAddr interface{}, networkID interface{}, txHash interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetDepositByHash_Call {
	return &bridgeServiceStorageMock_GetDepositByHash_Call{Call: _e.mock.On("GetDepositByHash", ctx, destAddr, networkID, txHash, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetDepositByHash_Call) Run(run func(ctx context.Context, destAddr string, networkID uint, txHash string, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetDepositByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint), args[3].(string), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositByHash_Call) Return(_a0 *etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetDepositByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositByHash_Call) RunAndReturn(run func(context.Context, string, uint, string, pgx.Tx) (*etherman.Deposit, error)) *bridgeServiceStorageMock_GetDepositByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepositCount provides a mock function with given fields: ctx, destAddr, dbTx
func (_m *bridgeServiceStorageMock) GetDepositCount(ctx context.Context, destAddr string, dbTx pgx.Tx) (uint64, error) {
	ret := _m.Called(ctx, destAddr, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDepositCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pgx.Tx) (uint64, error)); ok {
		return rf(ctx, destAddr, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pgx.Tx) uint64); ok {
		r0 = rf(ctx, destAddr, dbTx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetDepositCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepositCount'
type bridgeServiceStorageMock_GetDepositCount_Call struct {
	*mock.Call
}

// GetDepositCount is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetDepositCount(ctx interface{}, destAddr interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetDepositCount_Call {
	return &bridgeServiceStorageMock_GetDepositCount_Call{Call: _e.mock.On("GetDepositCount", ctx, destAddr, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetDepositCount_Call) Run(run func(ctx context.Context, destAddr string, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetDepositCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositCount_Call) Return(_a0 uint64, _a1 error) *bridgeServiceStorageMock_GetDepositCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositCount_Call) RunAndReturn(run func(context.Context, string, pgx.Tx) (uint64, error)) *bridgeServiceStorageMock_GetDepositCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepositCountByRoot provides a mock function with given fields: ctx, root, network, dbTx
func (_m *bridgeServiceStorageMock) GetDepositCountByRoot(ctx context.Context, root []byte, network uint32, dbTx pgx.Tx) (uint32, error) {
	ret := _m.Called(ctx, root, network, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDepositCountByRoot")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint32, pgx.Tx) (uint32, error)); ok {
		return rf(ctx, root, network, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint32, pgx.Tx) uint32); ok {
		r0 = rf(ctx, root, network, dbTx)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, root, network, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetDepositCountByRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepositCountByRoot'
type bridgeServiceStorageMock_GetDepositCountByRoot_Call struct {
	*mock.Call
}

// GetDepositCountByRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - root []byte
//   - network uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetDepositCountByRoot(ctx interface{}, root interface{}, network interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetDepositCountByRoot_Call {
	return &bridgeServiceStorageMock_GetDepositCountByRoot_Call{Call: _e.mock.On("GetDepositCountByRoot", ctx, root, network, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetDepositCountByRoot_Call) Run(run func(ctx context.Context, root []byte, network uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetDepositCountByRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(uint32), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositCountByRoot_Call) Return(_a0 uint32, _a1 error) *bridgeServiceStorageMock_GetDepositCountByRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositCountByRoot_Call) RunAndReturn(run func(context.Context, []byte, uint32, pgx.Tx) (uint32, error)) *bridgeServiceStorageMock_GetDepositCountByRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeposits provides a mock function with given fields: ctx, destAddr, limit, offset, dbTx
func (_m *bridgeServiceStorageMock) GetDeposits(ctx context.Context, destAddr string, limit uint32, offset uint32, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, destAddr, limit, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeposits")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, uint32, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, destAddr, limit, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, uint32, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, destAddr, limit, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, limit, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetDeposits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeposits'
type bridgeServiceStorageMock_GetDeposits_Call struct {
	*mock.Call
}

// GetDeposits is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - limit uint32
//   - offset uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetDeposits(ctx interface{}, destAddr interface{}, limit interface{}, offset interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetDeposits_Call {
	return &bridgeServiceStorageMock_GetDeposits_Call{Call: _e.mock.On("GetDeposits", ctx, destAddr, limit, offset, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetDeposits_Call) Run(run func(ctx context.Context, destAddr string, limit uint32, offset uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetDeposits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint32), args[3].(uint32), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetDeposits_Call) Return(_a0 []*etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetDeposits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetDeposits_Call) RunAndReturn(run func(context.Context, string, uint32, uint32, pgx.Tx) ([]*etherman.Deposit, error)) *bridgeServiceStorageMock_GetDeposits_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepositsForUnitTest provides a mock function with given fields: ctx, destAddr, limit, offset, dbTx
func (_m *bridgeServiceStorageMock) GetDepositsForUnitTest(ctx context.Context, destAddr string, limit uint, offset uint, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, destAddr, limit, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDepositsForUnitTest")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, destAddr, limit, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, destAddr, limit, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, limit, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetDepositsForUnitTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepositsForUnitTest'
type bridgeServiceStorageMock_GetDepositsForUnitTest_Call struct {
	*mock.Call
}

// GetDepositsForUnitTest is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - limit uint
//   - offset uint
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetDepositsForUnitTest(ctx interface{}, destAddr interface{}, limit interface{}, offset interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetDepositsForUnitTest_Call {
	return &bridgeServiceStorageMock_GetDepositsForUnitTest_Call{Call: _e.mock.On("GetDepositsForUnitTest", ctx, destAddr, limit, offset, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetDepositsForUnitTest_Call) Run(run func(ctx context.Context, destAddr string, limit uint, offset uint, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetDepositsForUnitTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint), args[3].(uint), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositsForUnitTest_Call) Return(_a0 []*etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetDepositsForUnitTest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositsForUnitTest_Call) RunAndReturn(run func(context.Context, string, uint, uint, pgx.Tx) ([]*etherman.Deposit, error)) *bridgeServiceStorageMock_GetDepositsForUnitTest_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepositsXLayer provides a mock function with given fields: ctx, destAddr, limit, offset, messageAllowlist, dbTx
func (_m *bridgeServiceStorageMock) GetDepositsXLayer(ctx context.Context, destAddr string, limit uint, offset uint, messageAllowlist []common.Address, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, destAddr, limit, offset, messageAllowlist, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetDepositsXLayer")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, []common.Address, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, destAddr, limit, offset, messageAllowlist, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, []common.Address, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, destAddr, limit, offset, messageAllowlist, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, []common.Address, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, limit, offset, messageAllowlist, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetDepositsXLayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepositsXLayer'
type bridgeServiceStorageMock_GetDepositsXLayer_Call struct {
	*mock.Call
}

// GetDepositsXLayer is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - limit uint
//   - offset uint
//   - messageAllowlist []common.Address
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetDepositsXLayer(ctx interface{}, destAddr interface{}, limit interface{}, offset interface{}, messageAllowlist interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetDepositsXLayer_Call {
	return &bridgeServiceStorageMock_GetDepositsXLayer_Call{Call: _e.mock.On("GetDepositsXLayer", ctx, destAddr, limit, offset, messageAllowlist, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetDepositsXLayer_Call) Run(run func(ctx context.Context, destAddr string, limit uint, offset uint, messageAllowlist []common.Address, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetDepositsXLayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint), args[3].(uint), args[4].([]common.Address), args[5].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositsXLayer_Call) Return(_a0 []*etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetDepositsXLayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetDepositsXLayer_Call) RunAndReturn(run func(context.Context, string, uint, uint, []common.Address, pgx.Tx) ([]*etherman.Deposit, error)) *bridgeServiceStorageMock_GetDepositsXLayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetL1ExitRootByGER provides a mock function with given fields: ctx, ger, dbTx
func (_m *bridgeServiceStorageMock) GetL1ExitRootByGER(ctx context.Context, ger common.Hash, dbTx pgx.Tx) (*etherman.GlobalExitRoot, error) {
	ret := _m.Called(ctx, ger, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetL1ExitRootByGER")
	}

	var r0 *etherman.GlobalExitRoot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, pgx.Tx) (*etherman.GlobalExitRoot, error)); ok {
		return rf(ctx, ger, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, pgx.Tx) *etherman.GlobalExitRoot); ok {
		r0 = rf(ctx, ger, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.GlobalExitRoot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash, pgx.Tx) error); ok {
		r1 = rf(ctx, ger, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetL1ExitRootByGER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL1ExitRootByGER'
type bridgeServiceStorageMock_GetL1ExitRootByGER_Call struct {
	*mock.Call
}

// GetL1ExitRootByGER is a helper method to define mock.On call
//   - ctx context.Context
//   - ger common.Hash
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetL1ExitRootByGER(ctx interface{}, ger interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetL1ExitRootByGER_Call {
	return &bridgeServiceStorageMock_GetL1ExitRootByGER_Call{Call: _e.mock.On("GetL1ExitRootByGER", ctx, ger, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetL1ExitRootByGER_Call) Run(run func(ctx context.Context, ger common.Hash, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetL1ExitRootByGER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetL1ExitRootByGER_Call) Return(_a0 *etherman.GlobalExitRoot, _a1 error) *bridgeServiceStorageMock_GetL1ExitRootByGER_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetL1ExitRootByGER_Call) RunAndReturn(run func(context.Context, common.Hash, pgx.Tx) (*etherman.GlobalExitRoot, error)) *bridgeServiceStorageMock_GetL1ExitRootByGER_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestExitRoot provides a mock function with given fields: ctx, networkID, destNetwork, dbTx
func (_m *bridgeServiceStorageMock) GetLatestExitRoot(ctx context.Context, networkID uint32, destNetwork uint32, dbTx pgx.Tx) (*etherman.GlobalExitRoot, error) {
	ret := _m.Called(ctx, networkID, destNetwork, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestExitRoot")
	}

	var r0 *etherman.GlobalExitRoot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) (*etherman.GlobalExitRoot, error)); ok {
		return rf(ctx, networkID, destNetwork, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) *etherman.GlobalExitRoot); ok {
		r0 = rf(ctx, networkID, destNetwork, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.GlobalExitRoot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, networkID, destNetwork, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetLatestExitRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestExitRoot'
type bridgeServiceStorageMock_GetLatestExitRoot_Call struct {
	*mock.Call
}

// GetLatestExitRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID uint32
//   - destNetwork uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetLatestExitRoot(ctx interface{}, networkID interface{}, destNetwork interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetLatestExitRoot_Call {
	return &bridgeServiceStorageMock_GetLatestExitRoot_Call{Call: _e.mock.On("GetLatestExitRoot", ctx, networkID, destNetwork, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetLatestExitRoot_Call) Run(run func(ctx context.Context, networkID uint32, destNetwork uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetLatestExitRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetLatestExitRoot_Call) Return(_a0 *etherman.GlobalExitRoot, _a1 error) *bridgeServiceStorageMock_GetLatestExitRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetLatestExitRoot_Call) RunAndReturn(run func(context.Context, uint32, uint32, pgx.Tx) (*etherman.GlobalExitRoot, error)) *bridgeServiceStorageMock_GetLatestExitRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotReadyTransactions provides a mock function with given fields: ctx, limit, offset, dbTx
func (_m *bridgeServiceStorageMock) GetNotReadyTransactions(ctx context.Context, limit uint, offset uint, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, limit, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetNotReadyTransactions")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, limit, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, limit, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, pgx.Tx) error); ok {
		r1 = rf(ctx, limit, offset, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetNotReadyTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotReadyTransactions'
type bridgeServiceStorageMock_GetNotReadyTransactions_Call struct {
	*mock.Call
}

// GetNotReadyTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint
//   - offset uint
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetNotReadyTransactions(ctx interface{}, limit interface{}, offset interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetNotReadyTransactions_Call {
	return &bridgeServiceStorageMock_GetNotReadyTransactions_Call{Call: _e.mock.On("GetNotReadyTransactions", ctx, limit, offset, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetNotReadyTransactions_Call) Run(run func(ctx context.Context, limit uint, offset uint, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetNotReadyTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetNotReadyTransactions_Call) Return(_a0 []*etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetNotReadyTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetNotReadyTransactions_Call) RunAndReturn(run func(context.Context, uint, uint, pgx.Tx) ([]*etherman.Deposit, error)) *bridgeServiceStorageMock_GetNotReadyTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingDepositsToClaim provides a mock function with given fields: ctx, destAddress, destNetwork, leafType, limit, offset, dbTx
func (_m *bridgeServiceStorageMock) GetPendingDepositsToClaim(ctx context.Context, destAddress common.Address, destNetwork uint32, leafType uint32, limit uint32, offset uint32, dbTx pgx.Tx) ([]*etherman.Deposit, uint64, error) {
	ret := _m.Called(ctx, destAddress, destNetwork, leafType, limit, offset, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingDepositsToClaim")
	}

	var r0 []*etherman.Deposit
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint32, uint32, uint32, uint32, pgx.Tx) ([]*etherman.Deposit, uint64, error)); ok {
		return rf(ctx, destAddress, destNetwork, leafType, limit, offset, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint32, uint32, uint32, uint32, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, destAddress, destNetwork, leafType, limit, offset, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, uint32, uint32, uint32, uint32, pgx.Tx) uint64); ok {
		r1 = rf(ctx, destAddress, destNetwork, leafType, limit, offset, dbTx)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.Address, uint32, uint32, uint32, uint32, pgx.Tx) error); ok {
		r2 = rf(ctx, destAddress, destNetwork, leafType, limit, offset, dbTx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// bridgeServiceStorageMock_GetPendingDepositsToClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingDepositsToClaim'
type bridgeServiceStorageMock_GetPendingDepositsToClaim_Call struct {
	*mock.Call
}

// GetPendingDepositsToClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddress common.Address
//   - destNetwork uint32
//   - leafType uint32
//   - limit uint32
//   - offset uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetPendingDepositsToClaim(ctx interface{}, destAddress interface{}, destNetwork interface{}, leafType interface{}, limit interface{}, offset interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetPendingDepositsToClaim_Call {
	return &bridgeServiceStorageMock_GetPendingDepositsToClaim_Call{Call: _e.mock.On("GetPendingDepositsToClaim", ctx, destAddress, destNetwork, leafType, limit, offset, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetPendingDepositsToClaim_Call) Run(run func(ctx context.Context, destAddress common.Address, destNetwork uint32, leafType uint32, limit uint32, offset uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetPendingDepositsToClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(uint32), args[3].(uint32), args[4].(uint32), args[5].(uint32), args[6].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetPendingDepositsToClaim_Call) Return(_a0 []*etherman.Deposit, _a1 uint64, _a2 error) *bridgeServiceStorageMock_GetPendingDepositsToClaim_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *bridgeServiceStorageMock_GetPendingDepositsToClaim_Call) RunAndReturn(run func(context.Context, common.Address, uint32, uint32, uint32, uint32, pgx.Tx) ([]*etherman.Deposit, uint64, error)) *bridgeServiceStorageMock_GetPendingDepositsToClaim_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingTransactions provides a mock function with given fields: ctx, destAddr, limit, offset, messageAllowlist, dbTx
func (_m *bridgeServiceStorageMock) GetPendingTransactions(ctx context.Context, destAddr string, limit uint, offset uint, messageAllowlist []common.Address, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, destAddr, limit, offset, messageAllowlist, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingTransactions")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, []common.Address, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, destAddr, limit, offset, messageAllowlist, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, []common.Address, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, destAddr, limit, offset, messageAllowlist, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, []common.Address, pgx.Tx) error); ok {
		r1 = rf(ctx, destAddr, limit, offset, messageAllowlist, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetPendingTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingTransactions'
type bridgeServiceStorageMock_GetPendingTransactions_Call struct {
	*mock.Call
}

// GetPendingTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - destAddr string
//   - limit uint
//   - offset uint
//   - messageAllowlist []common.Address
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetPendingTransactions(ctx interface{}, destAddr interface{}, limit interface{}, offset interface{}, messageAllowlist interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetPendingTransactions_Call {
	return &bridgeServiceStorageMock_GetPendingTransactions_Call{Call: _e.mock.On("GetPendingTransactions", ctx, destAddr, limit, offset, messageAllowlist, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetPendingTransactions_Call) Run(run func(ctx context.Context, destAddr string, limit uint, offset uint, messageAllowlist []common.Address, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetPendingTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint), args[3].(uint), args[4].([]common.Address), args[5].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetPendingTransactions_Call) Return(_a0 []*etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetPendingTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetPendingTransactions_Call) RunAndReturn(run func(context.Context, string, uint, uint, []common.Address, pgx.Tx) ([]*etherman.Deposit, error)) *bridgeServiceStorageMock_GetPendingTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetReadyPendingTransactions provides a mock function with given fields: ctx, networkID, limit, offset, minReadyTime, dbTx
func (_m *bridgeServiceStorageMock) GetReadyPendingTransactions(ctx context.Context, networkID uint, limit uint, offset uint, minReadyTime time.Time, dbTx pgx.Tx) ([]*etherman.Deposit, error) {
	ret := _m.Called(ctx, networkID, limit, offset, minReadyTime, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetReadyPendingTransactions")
	}

	var r0 []*etherman.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint, time.Time, pgx.Tx) ([]*etherman.Deposit, error)); ok {
		return rf(ctx, networkID, limit, offset, minReadyTime, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint, time.Time, pgx.Tx) []*etherman.Deposit); ok {
		r0 = rf(ctx, networkID, limit, offset, minReadyTime, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*etherman.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, uint, time.Time, pgx.Tx) error); ok {
		r1 = rf(ctx, networkID, limit, offset, minReadyTime, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetReadyPendingTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReadyPendingTransactions'
type bridgeServiceStorageMock_GetReadyPendingTransactions_Call struct {
	*mock.Call
}

// GetReadyPendingTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID uint
//   - limit uint
//   - offset uint
//   - minReadyTime time.Time
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetReadyPendingTransactions(ctx interface{}, networkID interface{}, limit interface{}, offset interface{}, minReadyTime interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetReadyPendingTransactions_Call {
	return &bridgeServiceStorageMock_GetReadyPendingTransactions_Call{Call: _e.mock.On("GetReadyPendingTransactions", ctx, networkID, limit, offset, minReadyTime, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetReadyPendingTransactions_Call) Run(run func(ctx context.Context, networkID uint, limit uint, offset uint, minReadyTime time.Time, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetReadyPendingTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(uint), args[4].(time.Time), args[5].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetReadyPendingTransactions_Call) Return(_a0 []*etherman.Deposit, _a1 error) *bridgeServiceStorageMock_GetReadyPendingTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetReadyPendingTransactions_Call) RunAndReturn(run func(context.Context, uint, uint, uint, time.Time, pgx.Tx) ([]*etherman.Deposit, error)) *bridgeServiceStorageMock_GetReadyPendingTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRollupExitLeavesByRoot provides a mock function with given fields: ctx, root, dbTx
func (_m *bridgeServiceStorageMock) GetRollupExitLeavesByRoot(ctx context.Context, root common.Hash, dbTx pgx.Tx) ([]etherman.RollupExitLeaf, error) {
	ret := _m.Called(ctx, root, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetRollupExitLeavesByRoot")
	}

	var r0 []etherman.RollupExitLeaf
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, pgx.Tx) ([]etherman.RollupExitLeaf, error)); ok {
		return rf(ctx, root, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash, pgx.Tx) []etherman.RollupExitLeaf); ok {
		r0 = rf(ctx, root, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]etherman.RollupExitLeaf)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash, pgx.Tx) error); ok {
		r1 = rf(ctx, root, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRollupExitLeavesByRoot'
type bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call struct {
	*mock.Call
}

// GetRollupExitLeavesByRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - root common.Hash
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetRollupExitLeavesByRoot(ctx interface{}, root interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call {
	return &bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call{Call: _e.mock.On("GetRollupExitLeavesByRoot", ctx, root, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call) Run(run func(ctx context.Context, root common.Hash, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call) Return(_a0 []etherman.RollupExitLeaf, _a1 error) *bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call) RunAndReturn(run func(context.Context, common.Hash, pgx.Tx) ([]etherman.RollupExitLeaf, error)) *bridgeServiceStorageMock_GetRollupExitLeavesByRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoot provides a mock function with given fields: ctx, depositCnt, network, dbTx
func (_m *bridgeServiceStorageMock) GetRoot(ctx context.Context, depositCnt uint32, network uint32, dbTx pgx.Tx) ([]byte, error) {
	ret := _m.Called(ctx, depositCnt, network, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoot")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) ([]byte, error)); ok {
		return rf(ctx, depositCnt, network, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, pgx.Tx) []byte); ok {
		r0 = rf(ctx, depositCnt, network, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, pgx.Tx) error); ok {
		r1 = rf(ctx, depositCnt, network, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoot'
type bridgeServiceStorageMock_GetRoot_Call struct {
	*mock.Call
}

// GetRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCnt uint32
//   - network uint32
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetRoot(ctx interface{}, depositCnt interface{}, network interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetRoot_Call {
	return &bridgeServiceStorageMock_GetRoot_Call{Call: _e.mock.On("GetRoot", ctx, depositCnt, network, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetRoot_Call) Run(run func(ctx context.Context, depositCnt uint32, network uint32, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetRoot_Call) Return(_a0 []byte, _a1 error) *bridgeServiceStorageMock_GetRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetRoot_Call) RunAndReturn(run func(context.Context, uint32, uint32, pgx.Tx) ([]byte, error)) *bridgeServiceStorageMock_GetRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenWrapped provides a mock function with given fields: ctx, originalNetwork, originalTokenAddress, dbTx
func (_m *bridgeServiceStorageMock) GetTokenWrapped(ctx context.Context, originalNetwork uint32, originalTokenAddress common.Address, dbTx pgx.Tx) (*etherman.TokenWrapped, error) {
	ret := _m.Called(ctx, originalNetwork, originalTokenAddress, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenWrapped")
	}

	var r0 *etherman.TokenWrapped
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, common.Address, pgx.Tx) (*etherman.TokenWrapped, error)); ok {
		return rf(ctx, originalNetwork, originalTokenAddress, dbTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, common.Address, pgx.Tx) *etherman.TokenWrapped); ok {
		r0 = rf(ctx, originalNetwork, originalTokenAddress, dbTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etherman.TokenWrapped)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, common.Address, pgx.Tx) error); ok {
		r1 = rf(ctx, originalNetwork, originalTokenAddress, dbTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// bridgeServiceStorageMock_GetTokenWrapped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenWrapped'
type bridgeServiceStorageMock_GetTokenWrapped_Call struct {
	*mock.Call
}

// GetTokenWrapped is a helper method to define mock.On call
//   - ctx context.Context
//   - originalNetwork uint32
//   - originalTokenAddress common.Address
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) GetTokenWrapped(ctx interface{}, originalNetwork interface{}, originalTokenAddress interface{}, dbTx interface{}) *bridgeServiceStorageMock_GetTokenWrapped_Call {
	return &bridgeServiceStorageMock_GetTokenWrapped_Call{Call: _e.mock.On("GetTokenWrapped", ctx, originalNetwork, originalTokenAddress, dbTx)}
}

func (_c *bridgeServiceStorageMock_GetTokenWrapped_Call) Run(run func(ctx context.Context, originalNetwork uint32, originalTokenAddress common.Address, dbTx pgx.Tx)) *bridgeServiceStorageMock_GetTokenWrapped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(common.Address), args[3].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_GetTokenWrapped_Call) Return(_a0 *etherman.TokenWrapped, _a1 error) *bridgeServiceStorageMock_GetTokenWrapped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *bridgeServiceStorageMock_GetTokenWrapped_Call) RunAndReturn(run func(context.Context, uint32, common.Address, pgx.Tx) (*etherman.TokenWrapped, error)) *bridgeServiceStorageMock_GetTokenWrapped_Call {
	_c.Call.Return(run)
	return _c
}

// SetBridgeBalance provides a mock function with given fields: ctx, originalTokenAddr, networkID, balance, dbTx
func (_m *bridgeServiceStorageMock) SetBridgeBalance(ctx context.Context, originalTokenAddr common.Address, networkID uint, balance *big.Int, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, originalTokenAddr, networkID, balance, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for SetBridgeBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint, *big.Int, pgx.Tx) error); ok {
		r0 = rf(ctx, originalTokenAddr, networkID, balance, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// bridgeServiceStorageMock_SetBridgeBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBridgeBalance'
type bridgeServiceStorageMock_SetBridgeBalance_Call struct {
	*mock.Call
}

// SetBridgeBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - originalTokenAddr common.Address
//   - networkID uint
//   - balance *big.Int
//   - dbTx pgx.Tx
func (_e *bridgeServiceStorageMock_Expecter) SetBridgeBalance(ctx interface{}, originalTokenAddr interface{}, networkID interface{}, balance interface{}, dbTx interface{}) *bridgeServiceStorageMock_SetBridgeBalance_Call {
	return &bridgeServiceStorageMock_SetBridgeBalance_Call{Call: _e.mock.On("SetBridgeBalance", ctx, originalTokenAddr, networkID, balance, dbTx)}
}

func (_c *bridgeServiceStorageMock_SetBridgeBalance_Call) Run(run func(ctx context.Context, originalTokenAddr common.Address, networkID uint, balance *big.Int, dbTx pgx.Tx)) *bridgeServiceStorageMock_SetBridgeBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(uint), args[3].(*big.Int), args[4].(pgx.Tx))
	})
	return _c
}

func (_c *bridgeServiceStorageMock_SetBridgeBalance_Call) Return(_a0 error) *bridgeServiceStorageMock_SetBridgeBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bridgeServiceStorageMock_SetBridgeBalance_Call) RunAndReturn(run func(context.Context, common.Address, uint, *big.Int, pgx.Tx) error) *bridgeServiceStorageMock_SetBridgeBalance_Call {
	_c.Call.Return(run)
	return _c
}

// newBridgeServiceStorageMock creates a new instance of bridgeServiceStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBridgeServiceStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *bridgeServiceStorageMock {
	mock := &bridgeServiceStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
