// Code generated by mockery. DO NOT EDIT.

package synchronizer

import (
	context "context"

	etherman "github.com/0xPolygonHermez/zkevm-bridge-service/etherman"
	mock "github.com/stretchr/testify/mock"
)

// bridgectrlMock is an autogenerated mock type for the bridgectrlInterface type
type bridgectrlMock struct {
	mock.Mock
}

type bridgectrlMock_Expecter struct {
	mock *mock.Mock
}

func (_m *bridgectrlMock) EXPECT() *bridgectrlMock_Expecter {
	return &bridgectrlMock_Expecter{mock: &_m.Mock}
}

// AddDeposit provides a mock function with given fields: ctx, deposit, dbTx
func (_m *bridgectrlMock) AddDeposit(ctx context.Context, deposit *etherman.Deposit, dbTx interface{}) error {
	ret := _m.Called(ctx, deposit, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddDeposit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *etherman.Deposit, interface{}) error); ok {
		r0 = rf(ctx, deposit, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// bridgectrlMock_AddDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDeposit'
type bridgectrlMock_AddDeposit_Call struct {
	*mock.Call
}

// AddDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - deposit *etherman.Deposit
//   - dbTx interface{}
func (_e *bridgectrlMock_Expecter) AddDeposit(ctx interface{}, deposit interface{}, dbTx interface{}) *bridgectrlMock_AddDeposit_Call {
	return &bridgectrlMock_AddDeposit_Call{Call: _e.mock.On("AddDeposit", ctx, deposit, dbTx)}
}

func (_c *bridgectrlMock_AddDeposit_Call) Run(run func(ctx context.Context, deposit *etherman.Deposit, dbTx interface{})) *bridgectrlMock_AddDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*etherman.Deposit), args[2].(interface{}))
	})
	return _c
}

func (_c *bridgectrlMock_AddDeposit_Call) Return(_a0 error) *bridgectrlMock_AddDeposit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bridgectrlMock_AddDeposit_Call) RunAndReturn(run func(context.Context, *etherman.Deposit, interface{}) error) *bridgectrlMock_AddDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// AddRollupExitLeaf provides a mock function with given fields: ctx, rollupLeaf, dbTx
func (_m *bridgectrlMock) AddRollupExitLeaf(ctx context.Context, rollupLeaf etherman.RollupExitLeaf, dbTx interface{}) error {
	ret := _m.Called(ctx, rollupLeaf, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddRollupExitLeaf")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, etherman.RollupExitLeaf, interface{}) error); ok {
		r0 = rf(ctx, rollupLeaf, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// bridgectrlMock_AddRollupExitLeaf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRollupExitLeaf'
type bridgectrlMock_AddRollupExitLeaf_Call struct {
	*mock.Call
}

// AddRollupExitLeaf is a helper method to define mock.On call
//   - ctx context.Context
//   - rollupLeaf etherman.RollupExitLeaf
//   - dbTx interface{}
func (_e *bridgectrlMock_Expecter) AddRollupExitLeaf(ctx interface{}, rollupLeaf interface{}, dbTx interface{}) *bridgectrlMock_AddRollupExitLeaf_Call {
	return &bridgectrlMock_AddRollupExitLeaf_Call{Call: _e.mock.On("AddRollupExitLeaf", ctx, rollupLeaf, dbTx)}
}

func (_c *bridgectrlMock_AddRollupExitLeaf_Call) Run(run func(ctx context.Context, rollupLeaf etherman.RollupExitLeaf, dbTx interface{})) *bridgectrlMock_AddRollupExitLeaf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(etherman.RollupExitLeaf), args[2].(interface{}))
	})
	return _c
}

func (_c *bridgectrlMock_AddRollupExitLeaf_Call) Return(_a0 error) *bridgectrlMock_AddRollupExitLeaf_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bridgectrlMock_AddRollupExitLeaf_Call) RunAndReturn(run func(context.Context, etherman.RollupExitLeaf, interface{}) error) *bridgectrlMock_AddRollupExitLeaf_Call {
	_c.Call.Return(run)
	return _c
}

// ReorgMT provides a mock function with given fields: ctx, depositCount, networkID, dbTx
func (_m *bridgectrlMock) ReorgMT(ctx context.Context, depositCount uint32, networkID uint32, dbTx interface{}) error {
	ret := _m.Called(ctx, depositCount, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for ReorgMT")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, interface{}) error); ok {
		r0 = rf(ctx, depositCount, networkID, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// bridgectrlMock_ReorgMT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReorgMT'
type bridgectrlMock_ReorgMT_Call struct {
	*mock.Call
}

// ReorgMT is a helper method to define mock.On call
//   - ctx context.Context
//   - depositCount uint32
//   - networkID uint32
//   - dbTx interface{}
func (_e *bridgectrlMock_Expecter) ReorgMT(ctx interface{}, depositCount interface{}, networkID interface{}, dbTx interface{}) *bridgectrlMock_ReorgMT_Call {
	return &bridgectrlMock_ReorgMT_Call{Call: _e.mock.On("ReorgMT", ctx, depositCount, networkID, dbTx)}
}

func (_c *bridgectrlMock_ReorgMT_Call) Run(run func(ctx context.Context, depositCount uint32, networkID uint32, dbTx interface{})) *bridgectrlMock_ReorgMT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(interface{}))
	})
	return _c
}

func (_c *bridgectrlMock_ReorgMT_Call) Return(_a0 error) *bridgectrlMock_ReorgMT_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bridgectrlMock_ReorgMT_Call) RunAndReturn(run func(context.Context, uint32, uint32, interface{}) error) *bridgectrlMock_ReorgMT_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackMT provides a mock function with given fields: ctx, networkID, dbTx
func (_m *bridgectrlMock) RollbackMT(ctx context.Context, networkID uint32, dbTx interface{}) error {
	ret := _m.Called(ctx, networkID, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackMT")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, interface{}) error); ok {
		r0 = rf(ctx, networkID, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// bridgectrlMock_RollbackMT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackMT'
type bridgectrlMock_RollbackMT_Call struct {
	*mock.Call
}

// RollbackMT is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID uint32
//   - dbTx interface{}
func (_e *bridgectrlMock_Expecter) RollbackMT(ctx interface{}, networkID interface{}, dbTx interface{}) *bridgectrlMock_RollbackMT_Call {
	return &bridgectrlMock_RollbackMT_Call{Call: _e.mock.On("RollbackMT", ctx, networkID, dbTx)}
}

func (_c *bridgectrlMock_RollbackMT_Call) Run(run func(ctx context.Context, networkID uint32, dbTx interface{})) *bridgectrlMock_RollbackMT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(interface{}))
	})
	return _c
}

func (_c *bridgectrlMock_RollbackMT_Call) Return(_a0 error) *bridgectrlMock_RollbackMT_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *bridgectrlMock_RollbackMT_Call) RunAndReturn(run func(context.Context, uint32, interface{}) error) *bridgectrlMock_RollbackMT_Call {
	_c.Call.Return(run)
	return _c
}

// newBridgectrlMock creates a new instance of bridgectrlMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBridgectrlMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *bridgectrlMock {
	mock := &bridgectrlMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
